apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
        - name: starbucks
          image: joshikunal/starbucks:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: apache-config
              mountPath: /etc/apache2/apache2.conf
              subPath: apache2.conf
            - mountPath: "/app/data"
              name: starbucks-storage
      volumes:
        - name: apache-config
          configMap:
            name: apache-config
        - name: starbucks-storage
          persistentVolumeClaim:
            claimName: pvc-starbucks
